package main

import (
	domain "github.com/udisondev/go-mapp/domain"
	dto "github.com/udisondev/go-mapp/dto"
	external "github.com/udisondev/go-mapp/external"
	user "github.com/udisondev/go-mapp/user"
)

// Code generated by go-mapp. DO NOT EDIT.
var mapMapPersonTypeToDto = map[domain.PersonType]dto.PersonType{domain.FUN: dto.Fun, domain.Simple: dto.Simple, domain.Important: dto.Important}

func MapPersonTypeToDto(pt domain.PersonType) (dto.PersonType, error) {
	t, ok := mapMapPersonTypeToDto[pt]
	if ok {
		return t, nil
	}

	return dto.Simple, nil
}

func MapPersonToDTO(src domain.Person) dto.Person {
	target := dto.Person{}

	if src.Firstname != nil {
		target.FirstName = *src.Firstname
	}
	target.LastName = src.LastName
	target.MiddleName = &src.MiddleName
	target.MainAccount = ecnyjwinwr(src.MainAccount)
	targetAccountSlice := make([]external.Account, 0, len(src.Account))
	for _, it := range src.Account {
		targetAccountSlice = append(targetAccountSlice, ecnyjwinwr(it))
	}
	target.Account = targetAccountSlice
	if src.Profile != nil {
		target.Profile = euplttaqsl(*src.Profile)
	}
	target.Projects = src.Projects

	return target
}

func ecnyjwinwr(src external.Account) external.Account {
	target := external.Account{}

	target.Login = dhgumkqmqh(src.Login)
	target.Password = src.Password

	return target
}

func dhgumkqmqh(src user.Login) user.Login {
	target := user.Login{}

	target.Value = src.Value

	return target
}

func euplttaqsl(src domain.Profile) dto.Profile {
	target := dto.Profile{}

	target.Phone = src.Number

	return target
}

func MapPersonToDomain(src dto.Person) domain.Person {
	target := domain.Person{}

	target.Firstname = &src.FirstName
	target.LastName = src.LastName
	if src.MiddleName != nil {
		target.MiddleName = *src.MiddleName
	}
	targetAccountSlice := make([]external.Account, 0, len(src.Account))
	for _, it := range src.Account {
		targetAccountSlice = append(targetAccountSlice, ecnyjwinwr(it))
	}
	target.Account = targetAccountSlice
	target.Projects = src.Projects

	return target
}
