package main

import (
	"fmt"
	domain "github.com/udisondev/go-mapp/domain"
	dto "github.com/udisondev/go-mapp/dto"
	external "github.com/udisondev/go-mapp/external"
	user "github.com/udisondev/go-mapp/user"
)

// Code generated by go-mapp. DO NOT EDIT.
var mapMapPersonTypeToDto = map[domain.PersonType]dto.PersonType{domain.Important: dto.Important, domain.FUN: dto.Fun, domain.Simple: dto.Simple}

func MapPersonTypeToDto(pt domain.PersonType) dto.PersonType {
	t, ok := mapMapPersonTypeToDto[pt]
	if ok {
		return t
	}

	panic(fmt.Sprintf("unsupported enum value: %v", pt))
}

var mapMapPersonTypeToDomain = map[dto.PersonType]domain.PersonType{dto.Important: domain.Important, dto.Fun: domain.FUN, dto.Simple: domain.Simple}

func MapPersonTypeToDomain(pt dto.PersonType) domain.PersonType {
	t, ok := mapMapPersonTypeToDomain[pt]
	if ok {
		return t
	}

	panic(fmt.Sprintf("unsupported enum value: %v", pt))
}

func MapPersonToDTO(src domain.Person) dto.Person {
	target := dto.Person{}

	if src.Firstname != nil {
		target.FirstName = *src.Firstname
	}
	target.LastName = src.LastName
	target.MiddleName = &src.MiddleName
	target.MainAccount = jnwvxspaun(src.MainAccount)
	targetAccountSlice := make([]external.Account, 0, len(src.Account))
	for _, it := range src.Account {
		targetAccountSlice = append(targetAccountSlice, jnwvxspaun(it))
	}
	target.Account = targetAccountSlice
	if src.Profile != nil {
		target.Profile = egjfkdpgdm(*src.Profile)
	}
	target.Type = MapPersonTypeToDto(src.Type)
	target.Projects = src.Projects

	return target
}

func jnwvxspaun(src external.Account) external.Account {
	target := external.Account{}

	target.Login = fgnpmqgvpy(src.Login)
	target.Password = src.Password

	return target
}

func fgnpmqgvpy(src user.Login) user.Login {
	target := user.Login{}

	target.Value = src.Value

	return target
}

func egjfkdpgdm(src domain.Profile) dto.Profile {
	target := dto.Profile{}

	target.Phone = src.Number

	return target
}

func MapPersonToDomain(src dto.Person) domain.Person {
	target := domain.Person{}

	target.Firstname = &src.FirstName
	target.LastName = src.LastName
	if src.MiddleName != nil {
		target.MiddleName = *src.MiddleName
	}
	targetAccountSlice := make([]external.Account, 0, len(src.Account))
	for _, it := range src.Account {
		targetAccountSlice = append(targetAccountSlice, jnwvxspaun(it))
	}
	target.Account = targetAccountSlice
	target.Type = MapPersonTypeToDomain(src.Type)
	target.Projects = src.Projects

	return target
}
