package main

import (
	"fmt"
	domain "github.com/udisondev/go-mapp/domain"
	dto "github.com/udisondev/go-mapp/dto"
	external "github.com/udisondev/go-mapp/external"
)

// Code generated by go-mapp. DO NOT EDIT.
func MapPersonTypeToDto(pt domain.PersonType) (dto.PersonType, error) {
	switch pt {
	case domain.Simple:
		return dto.Simple, nil
	case domain.Important:
		return dto.Important, nil
	case domain.FUN:
		return dto.Fun, nil
	default:
		return 0, fmt.Errorf("unknown source enum: %v", pt)
	}
}

func MapPersonTypeToDomain(pt dto.PersonType) (domain.PersonType, error) {
	switch pt {
	case dto.Simple:
		return domain.Simple, nil
	case dto.Important:
		return domain.Important, nil
	case dto.Fun:
		return domain.FUN, nil
	default:
		return domain.Vip, nil
	}
}

func MapPersonToDTO(src domain.Person) dto.Person {
	var mappedFirstName string
	var mappedAccount []external.Account
	var mappedProfile []dto.Profile
	var mappedType dto.PersonType
	return dto.Person{
		FirstName:   mappedFirstName,
		LastName:    src.LastName,
		MiddleName:  &src.MiddleName,
		Age:         src.Age,
		MainAccount: src.MainAccount,
		Account:     mappedAccount,
		Profile:     mappedProfile,
		Type:        mappedType,
		Projects:    src.Projects,
		// Email: ignored
	}
}
func MapPersonToDomain(src dto.Person) (domain.Person, error) {
	var mappedMiddleName string
	var mappedAccount []*external.Account
	var mappedProfile *[]domain.Profile
	var mappedType domain.PersonType
	return domain.Person{
		Firstname:  &src.FirstName,
		LastName:   src.LastName,
		MiddleName: mappedMiddleName,
		Age:        src.Age,
		// MainAccount: ignored
		Account:  mappedAccount,
		Profile:  mappedProfile,
		Type:     mappedType,
		Projects: src.Projects,
	}, nil
}
