package mapper

import (
	"fmt"
	domain "github.com/udisondev/go-mapp/domain"
	dto "github.com/udisondev/go-mapp/dto"
	external "github.com/udisondev/go-mapp/external"
)

// Code generated by go-mapp. DO NOT EDIT.
func MapPersonTypeToDto(pt domain.PersonType) (dto.PersonType, error) {
	switch pt {
	case domain.FUN:
		return dto.Fun, nil
	case domain.Simple:
		return dto.Simple, nil
	case domain.Important:
		return dto.Important, nil
	default:
		return 0, fmt.Errorf("unknown source enum: %v", pt)
	}
}

func MapPersonTypeToDomain(pt dto.PersonType) (domain.PersonType, error) {
	switch pt {
	case dto.Simple:
		return domain.Simple, nil
	case dto.Important:
		return domain.Important, nil
	case dto.Fun:
		return domain.FUN, nil
	default:
		return 0, fmt.Errorf("there is a cutome err. I dont want to handle this: %v", pt)
	}
}

func MapPersonToDTO(src domain.Person) dto.Person {
	var mappedFirstName string
	if src.Firstname != nil {
		mappedFirstName = *src.Firstname
	}
	var mappedAccount []external.Account
	for _, a := range src.Account {
		var AccountStruct external.Account
		if a != nil {
			AccountStruct = *a
		}
		mappedAccount = append(mappedAccount, AccountStruct)
	}
	var mappedProfile [][]dto.Profile
	if src.Profile != nil {
		for _, a := range *src.Profile {
			var ProfileSlice []dto.Profile
			for _, b := range a {
				var ProfileStruct dto.Profile
				var ProfileStructMappingErr error
				ProfileStruct, ProfileStructMappingErr = ryjfz(b)
				if ProfileStructMappingErr != nil {
					panic(fmt.Sprintf("'Profile' -> 'Profile': %v", ProfileStructMappingErr))
				}
				ProfileSlice = append(ProfileSlice, ProfileStruct)
			}
			mappedProfile = append(mappedProfile, ProfileSlice)
		}
	}
	var mappedType dto.PersonType
	var mappedTypeMappingErr error
	mappedType, mappedTypeMappingErr = MapPersonTypeToDto(src.Type)
	if mappedTypeMappingErr != nil {
		panic("Panic")
	}

	return dto.Person{
		FirstName:   mappedFirstName,
		LastName:    src.LastName,
		MiddleName:  &src.MiddleName,
		Age:         src.Age,
		MainAccount: src.MainAccount,
		Account:     mappedAccount,
		Profile:     mappedProfile,
		Type:        mappedType,
		Projects:    src.Projects,
		// Email: ignored
	}
}
func ryjfz(src domain.Profile) (dto.Profile, error) {
	var err error

	return dto.Profile{
		Phone: src.Number,
	}, err
}
func MapPersonToDomain(src dto.Person) (domain.Person, error) {
	var err error
	var mappedMiddleName string
	if src.MiddleName != nil {
		mappedMiddleName = *src.MiddleName
	}
	var mappedAccount []*external.Account
	for _, a := range src.Account {
		var AccountPointer *external.Account
		AccountPointer = &a
		mappedAccount = append(mappedAccount, AccountPointer)
	}
	var mappedProfile [][]domain.Profile
	for _, a := range src.Profile {
		var ProfileSlice []domain.Profile
		for _, b := range a {
			var ProfileStruct domain.Profile
			ProfileStruct, err = swpls(b)
			if err != nil {
				return domain.Person{}, fmt.Errorf("'Profile' -> 'Profile': %w", err)
			}
			ProfileSlice = append(ProfileSlice, ProfileStruct)
		}
		mappedProfile = append(mappedProfile, ProfileSlice)
	}
	var mappedType domain.PersonType
	mappedType, err = MapPersonTypeToDomain(src.Type)
	if err != nil {
		panic("Panic")
	}

	return domain.Person{
		Firstname:  &src.FirstName,
		LastName:   src.LastName,
		MiddleName: mappedMiddleName,
		Age:        src.Age,
		// MainAccount: ignored
		Account:  mappedAccount,
		Profile:  &mappedProfile,
		Type:     mappedType,
		Projects: src.Projects,
	}, err
}
func swpls(src dto.Profile) (domain.Profile, error) {
	var err error

	return domain.Profile{
		Number: src.Phone,
	}, err
}
